# Generated by Django 4.2.12 on 2025-06-01 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая стоимость')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.case', verbose_name='Корпус')),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.cpu', verbose_name='Процессор')),
                ('gpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.gpu', verbose_name='Видеокарта')),
                ('motherboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.motherboard', verbose_name='Материнская плата')),
                ('psu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.psu', verbose_name='Блок питания')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.ram', verbose_name='Оперативная память')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.storage', verbose_name='Накопитель')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сборка',
                'verbose_name_plural': 'Сборки',
            },
        ),
    ]
