# Generated by Django 4.2.12 on 2025-06-02 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('components', '0004_build'),
        ('builds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='build',
            name='case',
        ),
        migrations.RemoveField(
            model_name='build',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='build',
            name='gpu',
        ),
        migrations.RemoveField(
            model_name='build',
            name='motherboard',
        ),
        migrations.RemoveField(
            model_name='build',
            name='psu',
        ),
        migrations.RemoveField(
            model_name='build',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='build',
            name='storage',
        ),
        migrations.RemoveField(
            model_name='build',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='build',
            name='user',
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('build', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='builds.build', verbose_name='Сборка')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='components.case', verbose_name='Корпус')),
                ('cpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='components.cpu', verbose_name='Процессор')),
                ('gpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='components.gpu', verbose_name='Видеокарта')),
                ('motherboard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='components.motherboard', verbose_name='Материнская плата')),
                ('psu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='components.psu', verbose_name='Блок питания')),
                ('ram', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='components.ram', verbose_name='Оперативная память')),
                ('storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='components.storage', verbose_name='Накопитель')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Элемент корзины',
                'verbose_name_plural': 'Элементы корзины',
            },
        ),
    ]
