# Generated by Django 4.2.12 on 2025-06-03 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0009_alter_case_price_alter_cooler_price_alter_cpu_price_and_more'),
        ('builds', '0005_remove_cartitem_total_price_build_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='cooler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds', to='components.cooler', verbose_name='Охлаждение'),
        ),
    ]
