# Generated by Django 4.2.12 on 2025-06-06 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("builds", "0007_cartitem_cooler"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="build",
            options={},
        ),
    ]
