# Generated by Django 4.2.12 on 2025-06-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builds", "0008_alter_build_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="item_type",
            field=models.CharField(default="build", max_length=50),
            preserve_default=False,
        ),
    ]
