# Generated by Django 4.2.12 on 2025-06-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builds", "0012_order_is_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Заказ на рассмотрении"),
                    ("confirmed", "Заказ подтверждён"),
                    ("assembling", "Заказ собирается"),
                    ("delivery_prep", "Заказ готовится к доставке"),
                    ("delivering", "Заказ будет доставлен вам в течении 3 часов"),
                    ("delivered", "Заказ доставлен, заберите его"),
                    ("completed", "Заказ выполнен"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус заказа",
            ),
        ),
    ]
