# Generated by Django 4.2.12 on 2025-06-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builds", "0014_alter_order_delivery_option_alter_order_track_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="component_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="ID компонента"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="component_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cpu", "Процессор"),
                    ("gpu", "Видеокарта"),
                    ("motherboard", "Материнская плата"),
                    ("ram", "Оперативная память"),
                    ("storage", "Накопитель"),
                    ("psu", "Блок питания"),
                    ("case", "Корпус"),
                    ("cooler", "Охлаждение"),
                ],
                max_length=50,
                null=True,
                verbose_name="Тип компонента",
            ),
        ),
    ]
