# Generated by Django 4.2.12 on 2025-06-14 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("builds", "0015_orderitem_component_id_orderitem_component_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="item_type",
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="build",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="builds.build",
                verbose_name="Сборка",
            ),
        ),
    ]
