# Generated by Django 4.2.12 on 2025-06-15 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("builds", "0017_returnrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="return_request",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order",
                to="builds.returnrequest",
                verbose_name="Запрос на возврат",
            ),
        ),
    ]
