# Generated by Django 4.2.12 on 2025-07-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builds", "0019_cartitem_price_alter_build_total_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="price",
        ),
        migrations.AlterField(
            model_name="build",
            name="total_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Общая стоимость",
            ),
        ),
    ]
