# Generated by Django 4.2.12 on 2025-06-01 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0001_initial'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FPSData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_fps', models.IntegerField(verbose_name='FPS (минимальные)')),
                ('avg_fps', models.IntegerField(verbose_name='FPS (средние)')),
                ('max_fps', models.IntegerField(verbose_name='FPS (максимальные)')),
                ('settings', models.CharField(choices=[('low', 'Низкие'), ('medium', 'Средние'), ('high', 'Высокие'), ('ultra', 'Ультра')], default='medium', max_length=50, verbose_name='Настройки графики')),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.cpu', verbose_name='Процессор')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game', verbose_name='Игра')),
                ('gpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.gpu', verbose_name='Видеокарта')),
            ],
            options={
                'verbose_name': 'Данные FPS',
                'verbose_name_plural': 'Данные FPS',
            },
        ),
    ]
