# Generated by Django 4.2.12 on 2025-06-01 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('capacity', models.IntegerField(verbose_name='Объем (ГБ/ТБ)')),
                ('type', models.CharField(max_length=10, verbose_name='Тип (SSD/HDD)')),
                ('interface', models.CharField(max_length=50, verbose_name='Интерфейс')),
                ('read_speed', models.IntegerField(verbose_name='Скорость чтения (МБ/с)')),
                ('write_speed', models.IntegerField(verbose_name='Скорость записи (МБ/с)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Накопитель',
                'verbose_name_plural': 'Накопители',
            },
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('capacity', models.IntegerField(verbose_name='Объем (ГБ)')),
                ('frequency', models.IntegerField(verbose_name='Частота (МГц)')),
                ('type', models.CharField(max_length=10, verbose_name='Тип (DDR4, DDR5)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Оперативная память',
                'verbose_name_plural': 'Оперативная память',
            },
        ),
        migrations.CreateModel(
            name='PSU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('power', models.IntegerField(verbose_name='Мощность (Вт)')),
                ('certification', models.CharField(max_length=50, verbose_name='Сертификация')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Блок питания',
                'verbose_name_plural': 'Блоки питания',
            },
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('form_factor', models.CharField(max_length=50, verbose_name='Форм-фактор')),
                ('socket', models.CharField(max_length=50, verbose_name='Сокет')),
                ('chipset', models.CharField(max_length=50, verbose_name='Чипсет')),
                ('ram_slots', models.IntegerField(verbose_name='Слоты для RAM')),
                ('ram_type', models.CharField(max_length=10, verbose_name='Тип RAM (DDR4, DDR5)')),
                ('max_ram_frequency', models.IntegerField(verbose_name='Максимальная частота RAM')),
                ('expansion_slots', models.TextField(verbose_name='Слоты расширения')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Материнская плата',
                'verbose_name_plural': 'Материнские платы',
            },
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('memory', models.IntegerField(verbose_name='Объем памяти (ГБ)')),
                ('frequency', models.FloatField(verbose_name='Частота (ГГц)')),
                ('tdp', models.IntegerField(verbose_name='TDP (Вт)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Видеокарта',
                'verbose_name_plural': 'Видеокарты',
            },
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('cores', models.IntegerField(verbose_name='Количество ядер')),
                ('frequency', models.FloatField(verbose_name='Частота (ГГц)')),
                ('tdp', models.IntegerField(verbose_name='TDP (Вт)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('socket', models.CharField(max_length=50, verbose_name='Сокет')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Процессор',
                'verbose_name_plural': 'Процессоры',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('form_factor', models.CharField(max_length=50, verbose_name='Форм-фактор')),
                ('dimensions', models.CharField(max_length=50, verbose_name='Размеры')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Корпус',
                'verbose_name_plural': 'Корпуса',
            },
        ),
    ]
