# Generated by Django 4.2.12 on 2025-06-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_manufacturer_component_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='case_images/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cpu_images/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='gpu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gpu_images/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='motherboard_images/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='psu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='psu_images/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='ram',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ram_images/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='storage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='storage_images/', verbose_name='Изображение'),
        ),
    ]
