# Generated by Django 4.2.12 on 2025-06-03 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_build'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='build',
            options={'ordering': ['name'], 'verbose_name': 'Сборка', 'verbose_name_plural': 'Сборки'},
        ),
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['manufacturer', 'model'], 'verbose_name': 'Корпус', 'verbose_name_plural': 'Корпуса'},
        ),
        migrations.AlterModelOptions(
            name='cpu',
            options={'ordering': ['manufacturer', 'model'], 'verbose_name': 'Процессор', 'verbose_name_plural': 'Процессоры'},
        ),
        migrations.AlterModelOptions(
            name='gpu',
            options={'ordering': ['manufacturer', 'model'], 'verbose_name': 'Видеокарта', 'verbose_name_plural': 'Видеокарты'},
        ),
        migrations.AlterModelOptions(
            name='motherboard',
            options={'ordering': ['manufacturer', 'model'], 'verbose_name': 'Материнская плата', 'verbose_name_plural': 'Материнские платы'},
        ),
        migrations.AlterModelOptions(
            name='psu',
            options={'ordering': ['manufacturer', 'model'], 'verbose_name': 'Блок питания', 'verbose_name_plural': 'Блоки питания'},
        ),
        migrations.AlterModelOptions(
            name='ram',
            options={'ordering': ['manufacturer', 'model'], 'verbose_name': 'Оперативная память', 'verbose_name_plural': 'Оперативная память'},
        ),
        migrations.AlterModelOptions(
            name='storage',
            options={'ordering': ['manufacturer', 'model'], 'verbose_name': 'Накопитель', 'verbose_name_plural': 'Накопители'},
        ),
    ]
