# Generated by Django 4.2.12 on 2025-06-03 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0005_alter_build_options_alter_case_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('cooler_type', models.CharField(choices=[('air', 'Воздушное'), ('liquid', 'Жидкостное')], max_length=50, verbose_name='Тип охлаждения')),
                ('fan_size', models.IntegerField(blank=True, null=True, verbose_name='Размер вентилятора (мм)')),
                ('radiator_size', models.CharField(blank=True, max_length=50, null=True, verbose_name='Размер радиатора')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cooler_images/', verbose_name='Изображение')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Охлаждение',
                'verbose_name_plural': 'Охлаждения',
                'ordering': ['manufacturer', 'model'],
            },
        ),
    ]
