# Generated by Django 4.2.12 on 2025-06-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0006_cooler'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpu',
            name='interface',
            field=models.CharField(default='PCIe x16', max_length=50, verbose_name='Интерфейс'),
        ),
    ]
