# Generated by Django 4.2.12 on 2025-06-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0007_gpu_interface'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='supported_motherboard_form_factors',
            field=models.CharField(default='ATX, Micro-ATX, Mini-ITX', max_length=255, verbose_name='Поддерживаемые форм-факторы мат. плат'),
        ),
    ]
