# Generated by Django 4.2.12 on 2025-06-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "components",
            "0009_alter_case_price_alter_cooler_price_alter_cpu_price_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("cpu", "Процессор"),
                            ("gpu", "Видеокарта"),
                            ("motherboard", "Материнская плата"),
                            ("ram", "Оперативная память"),
                            ("storage", "Накопитель"),
                            ("psu", "Блок питания"),
                            ("case", "Корпус"),
                            ("cooler", "Охлаждение"),
                        ],
                        max_length=50,
                        verbose_name="Тип компонента",
                    ),
                ),
                (
                    "component_id",
                    models.PositiveIntegerField(verbose_name="ID компонента"),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=0, verbose_name="Количество"),
                ),
            ],
            options={
                "verbose_name": "Складской запас",
                "verbose_name_plural": "Складские запасы",
                "unique_together": {("component_type", "component_id")},
            },
        ),
    ]
