# Generated by Django 4.2.12 on 2025-06-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0011_alter_manufacturer_component_type_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manufacturer",
            name="component_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cpu", "Процессор"),
                    ("gpu", "Видеокарта"),
                    ("motherboard", "Материнская плата"),
                    ("ram", "Оперативная память"),
                    ("storage", "Накопитель"),
                    ("psu", "Блок питания"),
                    ("case", "Корпус"),
                    ("cooler", "Охлаждение"),
                ],
                max_length=50,
                null=True,
                verbose_name="Тип компонента",
            ),
        ),
    ]
