# Generated by Django 4.2.12 on 2025-07-01 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0013_case_side_panel_window_cooler_rgb_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="psu",
            unique_together={("manufacturer", "model")},
        ),
    ]
