# Generated by Django 4.2.12 on 2025-06-01 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('genre', models.CharField(max_length=255, verbose_name='Жанр')),
                ('min_ram', models.IntegerField(default=4, verbose_name='Мин. RAM (ГБ)')),
                ('recommended_ram', models.IntegerField(default=8, verbose_name='Реком. RAM (ГБ)')),
                ('min_cpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='min_games', to='components.cpu', verbose_name='Мин. CPU')),
                ('min_gpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='min_games', to='components.gpu', verbose_name='Мин. GPU')),
                ('recommended_cpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_games', to='components.cpu', verbose_name='Реком. CPU')),
                ('recommended_gpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_games', to='components.gpu', verbose_name='Реком. GPU')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
    ]
